{{- if and .Values.homelab.vaultAppRoleSealedSecret.enabled (not (empty .Values.homelab.vaultAppRoleSealedSecret.encryptedData)) }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.homelab.vault.authSecretName | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  template:
    metadata:
      name: {{ .Values.homelab.vault.authSecretName | quote }}
      namespace: {{ .Release.Namespace | quote }}
    type: Opaque
  encryptedData:
{{- range $k, $v := .Values.homelab.vaultAppRoleSealedSecret.encryptedData }}
    {{ $k }}: {{ $v }}
{{- end }}
{{- end }}
