apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plant-tracker-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: plant-tracker-secret
    creationPolicy: Owner
  data:
    - secretKey: "database-connection-string"
      remoteRef:
        key: "secrets/plant-tracker"
        property: "database-connection-string"
