apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: my-test-secret
    creationPolicy: Owner
  data:
    - secretKey: "MY-TEST-SECRET"
      remoteRef:
        key: "kubernetes-dev"
        property: "mysecret"
