apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault.skippythesnake.com"
      path: "secret/kubernetes-dev"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token

        # kubernetes:
        #   mountPath: "auth/kubernetes"
        #   role: "kubernetes-dev"
        #   serviceAccountRef:
        #     name: "external-secrets"
        #     namespace: "external-secrets"
