{{- include "common.externalSecret" (dict
  "name" .Values.homelab.externalSecret.name
  "remoteKey" .Values.homelab.externalSecret.remoteKey
  "refreshInterval" .Values.homelab.externalSecret.refreshInterval
  "clusterSecretStoreName" .Values.homelab.externalSecret.clusterSecretStoreName
  "enabled" .Values.homelab.externalSecret.enabled
  "secretEnv" (list
    (dict "secretKey" "admin-username" "property" .Values.homelab.externalSecret.usernameProperty)
    (dict "secretKey" "admin-password" "property" .Values.homelab.externalSecret.passwordProperty)
  )
) }}
