{{- if .Values.persistence.enabled }}
{{- include "common.persistentStorage" (dict "pvcName" "postgres-data" "size" .Values.persistence.size "storageClass" .Values.persistence.storageClassName) }}
{{- end }}
