image:
  repository: ghcr.io/recyclarr/recyclarr
  tag: "8"

schedule: "@daily"
timeZone: "Etc/UTC"

# Full contents of recyclarr.yml (see https://recyclarr.dev)
config: ""

homelab:
  externalSecret:
    enabled: false
    name: ""
  remoteKey: ""
  property: api_key
  secretKey: api-key
  envVarName: SONARR_API_KEY
