---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: skippythesnake-dev
  namespace: traefik
spec:
  secretName: skippythesnake-dev-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.dev.skippythesnake.com"
  dnsNames:
    - "*.dev.skippythesnake.com"
    - dev.skippythesnake.com
