---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: skippythesnake
  namespace: traefik
spec:
  secretName: skippythesnake-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.skippythesnake.com"
  dnsNames:
    - "*.skippythesnake.com"
    - skippythesnake.com
