version: "3.8"

services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - "{{ (appdata_path, 'nginx-proxy-manager/data') | path_join }}:/data"
      - "{{ (appdata_path, 'nginx-proxy-manager/letsencrypt') | path_join}}:/etc/letsencrypt"
    environment:
      - "USER_ID=99"
      - "GROUP_ID=100"
      - "UMASK=000"
