apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 9.5.4
      helm:
        valueFiles:
          - $values/kubernetes-v2/argocd/values.yaml
    - repoURL: https://github.com/ReidMason/homelab.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/ReidMason/homelab.git
      targetRevision: main
      path: kubernetes-v2/argocd/applicationsets
      directory:
        include: "*.yaml"
