apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/ReidMason/homelab.git
        revision: main
        directories:
          - path: "kubernetes-v2/charts/*"
  template:
    metadata:
      name: "{{path.basename}}"
      namespace: argocd
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/ReidMason/homelab.git
        targetRevision: main
        path: "{{path}}"
        helm:
          releaseName: "{{path.basename}}"
          valueFiles:
            - "values.yaml"
            # This is breaking things not sure why yet
            # - "../../values/dev/{{path.basename}}/values.yaml"
