{{- if .Values.persistence.enabled }}
{{- include "common.persistentStorage" (dict "pvcName" "sonarr-config" "pvName" (printf "%s-sonarr-config" .Release.Namespace) "size" .Values.persistence.size "storageClass" .Values.persistence.config.storageClass "nfs" .Values.persistence.config.nfs) }}
{{- end }}
