apiVersion: v1
kind: PersistentVolume
metadata:
  name: seerr-pv
  labels:
    type: seerr-storage
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/user/kubernetes/seerr
    server: fern.lan
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seerr-pvc
  namespace: seerr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: seerr-storage
