- name: Create data directories
  vars:
    service_name: "startpage"
    data_directories:
      - "startpage"
      - "startpage/static"
  ansible.builtin.import_role:
    name: docker-deploy
    tasks_from: create-container
