replicaCount: 0

persistence:
  config:
    storageClass: longhorn
  downloads:
    nfs:
      server: fern.internal
      path: /mnt/user/Downloads/qBittorrent/Completed
  tv:
    nfs:
      server: fern.internal
      path: /mnt/user/Plex

homelab:
  ingressRoute:
    enabled: true
    host: sonarr.skippythesnake.com
  lanService:
    enabled: true
    loadBalancerIP: 10.128.20.63
