apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkwarden-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: linkwarden-secret
    creationPolicy: Owner
  data:
    - secretKey: "database-url"
      remoteRef:
        key: "secrets/linkwarden"
        property: "database-url"
    - secretKey: "nextauth-secret"
      remoteRef:
        key: "secrets/linkwarden"
        property: "nextauth-secret"
