apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: valkey
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`valkey.skippythesnake.com`)
      services:
        - name: valkey
          port: 80
  tls:
    secretName: skippythesnake-tls
