apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: valkey
spec:
  entryPoints:
    - redis
  routes:
    - match: HostSNI(`*`)
      services:
        - name: valkey
          port: 80
