external-secrets:
  installCRDs: true
  bitwarden-sdk-server:
    enabled: false

homelab:
  clusterSecretStore:
    enabled: true
    name: vault-homelab
  vault:
    server: ""
    path: secret
    version: v2
    caBundle: ""
    auth:
      mountPath: approle
    authSecretName: vault-approle-eso
  vaultAppRoleSealedSecret:
    enabled: false
    encryptedData: {}
