image:
  repository: portainer/portainer-ce
  tag: "2.21.4"

persistence:
  enabled: true
  storageClass: nfs
  size: 10Gi
  storagePath: portainer

homelab:
  ingressRoute:
    enabled: false
    host: ""
    entryPoints:
      - websecure
    servicePort: 9443
    scheme: https
