image:
  repository: portainer/portainer-ce
  tag: "2.21.4"

persistence:
  enabled: true
  size: 10Gi
  nfs:
    server: fern.internal
    path: /mnt/user/kubernetes/portainer

homelab:
  ingressRoute:
    enabled: false
    host: ""
    entryPoints:
      - websecure
    servicePort: 9443
    scheme: https
