home_path: "{{ lookup('env', 'HOME') }}"
appdata_path: "{{ (home_path, 'appdata') | path_join }}"

packages:
  - neofetch
  - speedtest-cli
  - docker-compose

dockers:
  - uptime-kuma
  - portainer-agent
  - node-exporter
  - pi-hole

docker_install_compose: true
pip_install_packages:
  - name: docker
