apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: sonarr-theme
  namespace: traefik
spec:
  plugin:
    themepark:
      app: sonarr
      baseUrl: https://theme-park.dev
      theme: nord
