apiVersion: v1
kind: Service
metadata:
  namespace: traefik
  name: traefik-dashboard-service

spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: dashboard
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  namespace: traefik
  name: traefik-websecure-service

spec:
  type: LoadBalancer
  ports:
    - targetPort: websecure
      port: 443
  selector:
    app: traefik
