additionalArguments:
  - "--serversTransport.insecureSkipVerify=true" # This allows us to proxy to https services like portainer or argocd

# ports:
#   web:
#     redirectTo:
#       port: websecure
#       priority: 10
#   websecure:
#     tls:
#       enabled: true
ports:
  postgresql:
    port: 5432
    exposedPort: 5432
    protocol: TCP

ingressRoute:
  dashboard:
    enabled: true
    entryPoints:
      - websecure
    matchRule: Host(`traefik.skippythesnake.com`)

providers:
  kubernetesCRD:
    enabled: true
    allowExternalNameServices: true
    allowCrossNamespace: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    publishedService:
      enabled: false

service:
  enabled: true
  type: LoadBalancer
  spec:
    loadBalancerIP: "10.128.0.70"
    externalTrafficPolicy: Local

experimental:
  plugins:
    themepark:
      moduleName: "github.com/packruler/traefik-themepark"
      version: "v1.4.2"
