longhorn:
  persistence:
    defaultClassReplicaCount: 2
    recurringJobSelector:
      enable: true
      jobList: '[{"name":"daily-backup", "isGroup":false},{"name":"weekly-backup", "isGroup":false},{"name":"filesystem-trim", "isGroup":false}]'
  defaultSettings:
    defaultReplicaCount: "2"
  defaultBackupStore:
    backupTarget: "nfs://fern.internal:/mnt/user/Backups/longhorn"
    backupTargetCredentialSecret: ""
    pollInterval: 300
  longhornUI:
    replicas: 1

homelab:
  ingressRoute:
    enabled: true
    host: longhorn.skippythesnake.com
  backup:
    enabled: true
  trim:
    enabled: true
  metrics:
    enabled: true
