apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-worker
  labels:
    app: authentik-worker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: authentik-worker
  template:
    metadata:
      labels:
        app: authentik-worker
    spec:
      tolerations:
        - key: node.kubernetes.io/unreachable
          effect: NoExecute
          tolerationSeconds: 10
      containers:
        - name: authentik-worker
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          args: ["worker"]
          env:
            {{- include "authentik.env" . | nindent 12 }}
          volumeMounts:
            {{- include "authentik.volumeMounts" . | nindent 12 }}
      volumes:
        {{- include "authentik.volumes" . | nindent 8 }}
