{{- if .Values.persistence.enabled }}
{{- include "common.persistentStorage" (dict
  "pvName" (printf "%s-authentik-media" .Release.Namespace)
  "pvcName" "authentik-media"
  "size" .Values.persistence.size
  "nfs" .Values.persistence.nfs
) }}
{{- end }}
