nas_ip: "fern.lan"
host_ip: "vera.lan"

home_path: "{{ ansible_env.HOME }}"
nas_mount_point: "{{ (home_path, 'fern') | path_join  }}"

appdata_path: "{{ (home_path, 'appdata') | path_join  }}"
downloads_path: "{{ (nas_mount_point, 'downloads') | path_join }}"
plex_path: "{{ (nas_mount_point, 'plex') | path_join }}"

paths:
  - src: "//{{ nas_ip }}/appdata"
    path: "{{ (nas_mount_point, 'appdata') | path_join }}"
  - src: "//{{ nas_ip }}/Downloads"
    path: "{{ downloads_path }}"
  - src: "//{{ nas_ip }}/Plex"
    path: "{{ plex_path }}"

packages:
  - neofetch
  - speedtest-cli
  - docker-compose
  - cifs-utils

dockers:
  - startpage
  - downloads
  - portainer
  - discord-bot
  - nginx-proxy-manager
  - plex

docker_install_compose: true
pip_install_packages:
  - name: docker
