home_path: "{{ ansible_env.HOME }}"
nas_mount_point: "{{ (home_path, 'fern') | path_join  }}"

paths:
  - src: "{{ nas_ip }}:/mnt/user/Downloads"
    path: "{{ (nas_mount_point, 'downloads') | path_join }}"
    opts: "ro"
