apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  labels:
    app: discord-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      tolerations:
        - key: node.kubernetes.io/unreachable
          effect: NoExecute
          tolerationSeconds: 0
      containers:
        - name: discord-bot
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.homelab.externalSecret.name }}
                  key: {{ .Values.homelab.externalSecret.secretKey }}
