replicaCount: 1

hostNetwork: true

persistence:
  config:
    storageClass: longhorn

homelab:
  ingressRoute:
    enabled: true
    host: homeassistant.skippythesnake.com
    forwardAuth:
      enabled: false
