apiVersion: v2
name: portainer-agent
description: Portainer agent for in-cluster management
type: application
version: 0.1.0
dependencies:
  - name: common
    version: 0.3.0
    repository: "file://../common"
