services:
  "{{ service_name}}":
    container_name: "{{ service_name }}"
    image: quay.io/prometheus/node-exporter:v1.8.2
    command:
      - "--path.rootfs=/host"
    # network_mode: host
    ports:
      - 9100:9100
    pid: host
    restart: always
    volumes:
      - "/:/host:ro,rslave"
    networks:
      - skippynet

networks:
  skippynet:
    external: true
