apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      hostname: pihole
      tolerations:
        - key: node.kubernetes.io/unreachable
          effect: NoExecute
          tolerationSeconds: 0
      {{- if and .Values.persistence.enabled .Values.persistence.fixPermissions }}
      initContainers:
        - name: fix-nfs-permissions
          image: busybox:1.36
          command:
            - sh
            - -c
            - chown -R {{ .Values.persistence.uid }}:{{ .Values.persistence.gid }} /etc/pihole /etc/dnsmasq.d
          securityContext:
            runAsUser: 0
          volumeMounts:
            {{- range .Values.persistence.volumeMounts }}
            - name: pihole-storage
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
            {{- end }}
      {{- end }}
      containers:
        - name: pihole
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 67
            - containerPort: 80
          env:
            - name: PIHOLE_UID
              value: {{ .Values.persistence.uid | quote }}
            - name: PIHOLE_GID
              value: {{ .Values.persistence.gid | quote }}
            - name: TZ
              value: {{ .Values.env.tz | quote }}
            - name: WEBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.homelab.externalSecret.name }}
                  key: {{ .Values.homelab.externalSecret.secretKey }}
          volumeMounts:
            {{- range .Values.persistence.volumeMounts }}
            - name: pihole-storage
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
            {{- end }}
      volumes:
        - name: pihole-storage
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: pihole-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
