{{- if .Values.persistence.enabled }}
{{- include "common.persistentStorage" (dict "pvName" "pihole-pv" "pvcName" "pihole-pvc" "size" .Values.persistence.size "nfs" .Values.persistence.nfs) }}
{{- end }}
