apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
  {{- if .Values.homelab.dnsService.metallbAddressPool }}
  annotations:
    metallb.io/address-pool: {{ .Values.homelab.dnsService.metallbAddressPool | quote }}
  {{- end }}
spec:
  type: {{ .Values.homelab.dnsService.type }}
  selector:
    app: pihole
  ports:
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
  {{- if .Values.homelab.dnsService.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.homelab.dnsService.externalTrafficPolicy }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dashboard
spec:
  selector:
    app: pihole
  ports:
    - protocol: TCP
      name: webui
      port: 80
      targetPort: 80
