services:
  "{{ service_name}}":
    container_name: "{{ service_name }}"
    image: prom/prometheus:v2.54.1
    restart: always
    ports:
      - 9090:9090
    volumes:
      - "{{ (appdata_path, service_name, 'prometheus.yml') | path_join }}:/etc/prometheus/prometheus.yml"
      - "{{ (appdata_path, service_name, 'data') | path_join }}:/prometheus"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
    networks:
      - skippynet

networks:
  skippynet:
    external: true
