apiVersion: apps/v1
kind: Deployment
metadata:
  name: habit-tracker-api-deployment
  labels:
    app: habit-tracker-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: habit-tracker-api
  template:
    metadata:
      labels:
        app: habit-tracker-api
    spec:
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          effect: "NoExecute"
          tolerationSeconds: 0
      containers:
        - name: habit-tracker-api
          image: ghcr.io/reidmason/habit-tracker-api:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: habit-tracker-storage
              mountPath: /app/data
      volumes:
        - name: habit-tracker-storage
          persistentVolumeClaim:
            claimName: habit-tracker-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: habit-tracker-api-service-internal
spec:
  selector:
    app: habit-tracker-api
  ports:
    - protocol: TCP
      name: api
      port: 80
      targetPort: 8000

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: habit-tracker-pv
  labels:
    type: habit-tracker-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/user/Temp/habit-tracker
    server: fern.lan
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: habit-tracker-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: habit-tracker-storage
