apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: habit-tracker
  namespace: habit-tracker
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`habit.dev.skippythesnake.com`) && PathPrefix(`/`)
      kind: Rule
      middlewares:
        - name: default-headers
          namespace: traefik
      services:
        - name: habit-tracker-ui
          port: 80
    - match: Host(`habit.dev.skippythesnake.com`) && PathPrefix(`/api`)
      kind: Rule
      middlewares:
        - name: default-headers
          namespace: traefik
      services:
        - name: habit-tracker-api
          port: 80
  tls:
    secretName: skippythesnake-dev-tls
