apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: habit-tracker
  name: habit-tracker-api-ingress
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: habit-tracker-api-service-internal
                port:
                  name: api
          - path: /
            pathType: Prefix
            backend:
              service:
                name: habit-tracker-ui-service-internal
                port:
                  name: api
