version: "3.8"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    volumes:
      - "{{ (appdata_path, 'uptime-kuma') | path_join }}:/app/data"
    ports:
      - 3001:3001
