apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-notifier
  labels:
    app: relay-notifier
spec:
  replicas: {{ .Values.notifier.replicaCount }}
  selector:
    matchLabels:
      app: relay-notifier
  template:
    metadata:
      labels:
        app: relay-notifier
    spec:
      tolerations:
        - key: node.kubernetes.io/unreachable
          effect: NoExecute
          tolerationSeconds: 10
      containers:
        - name: relay-notifier
          image: {{ .Values.notifier.image.repository }}:{{ .Values.notifier.image.tag }}
          imagePullPolicy: Always
          env:
            - name: NATS_URL
              value: {{ .Values.natsUrl | quote }}
            - name: PORT
              value: {{ .Values.notifier.port | quote }}
            - name: DISCORD_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.notifier.homelab.externalSecret.name }}
                  key: {{ .Values.notifier.homelab.externalSecret.secretKey }}
          ports:
            - containerPort: {{ .Values.notifier.port }}
              name: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.notifier.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /livez
              port: {{ .Values.notifier.port }}
            initialDelaySeconds: 5
            periodSeconds: 15
