apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pihole
  namespace: pihole
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pihole-kube.skippythesnake.com`)
      kind: Rule
      services:
        - name: pihole-dashboard
          port: 80
