apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pihole-secret
  namespace: pihole
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pihole-secret
    creationPolicy: Owner
  data:
    - secretKey: "webui-password"
      remoteRef:
        key: "secrets/pihole"
        property: "webui-password"
