apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
spec:
  project: default
  source:
    repoURL: https://github.com/ReidMason/homelab.git
    targetRevision: HEAD
    path: kubernetes/postgresql
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
