apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cf-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cloudflare-token-secret
    creationPolicy: Owner
  data:
    - secretKey: "cloudflare-token"
      remoteRef:
        key: "secrets-dev/cloudflare"
        property: "letsencrypt-token"
---
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   namespace: cert-manager
#   name: letsencrypt-production
# spec:
#   acme:
#     server: https://acme-v02.api.letsencrypt.org/directory
#     email: maddogshain132@gmail.com
#     privateKeySecretRef:
#       name: letsencrypt-production
#     solvers:
#       - dns01:
#           cloudflare:
#             email: maddogshain132@gmail.com
#             apiKeySecretRef:
#               name: cloudflare-token-secret
#               key: cloudflare-token
#
#         selector:
#           dnsZones:
#             - "skippythesnake.com"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  namespace: cert-manager
  name: letsencrypt-dev
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: maddogshain132@gmail.com
    privateKeySecretRef:
      name: letsencrypt-dev
    solvers:
      - dns01:
          cloudflare:
            email: maddogshain132@gmail.com
            apiKeySecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token

        selector:
          dnsZones:
            - "skippythesnake.com"
