services:
  "{{ service_name }}":
    container_name: "{{ service_name }}"
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 9443:9443
    volumes:
      - "{{ (appdata_path, service_name) | path_join }}:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - skippynet

networks:
  skippynet:
    external: true
