services:
  "{{ service_name }}":
    container_name: "{{ service_name }}"
    image: "docker.io/jc21/nginx-proxy-manager:2.11.3"
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - "{{ (appdata_path, service_name, 'data') | path_join }}:/data"
      - "{{ (appdata_path, service_name, 'letsencrypt') | path_join}}:/etc/letsencrypt"
    environment:
      - "USER_ID=99"
      - "GROUP_ID=100"
      - "UMASK=000"
    networks:
      - skippynet

networks:
  skippynet:
    name: skippynet
