homelab:
  externalSecret:
    enabled: true
    remoteKey: secret/dev/cloudflare
    property: letsencrypt-token

  argocdIngressRoute:
    enabled: true
    host: argocd.dev.skippythesnake.com

traefik:
  additionalArguments:
    - "--serversTransport.insecureSkipVerify=true"
    - "--certificatesresolvers.letsencrypt.acme.domains[0].main=*.dev.skippythesnake.com"
    - "--certificatesresolvers.letsencrypt.acme.domains[0].sans=dev.skippythesnake.com"

  service:
    spec:
      loadBalancerIP: "10.128.30.60"

  ingressRoute:
    dashboard:
      matchRule: Host(`traefik.dev.skippythesnake.com`)
