homelab:
  externalSecret:
    enabled: false

  argocdIngressRoute:
    enabled: true
    host: argocd.dev.skippythesnake.com

  certManagerTls:
    enabled: true
    certificateName: skippythesnake-dev
    secretName: skippythesnake-dev-tls
    issuerRef:
      name: letsencrypt-production
      kind: ClusterIssuer
    commonName: "*.dev.skippythesnake.com"
    dnsNames:
      - "*.dev.skippythesnake.com"
      - dev.skippythesnake.com

traefik:
  additionalArguments:
    - "--serversTransport.insecureSkipVerify=true"

  service:
    spec:
      loadBalancerIP: "10.128.30.60"

  ingressRoute:
    dashboard:
      matchRule: Host(`traefik.dev.skippythesnake.com`)
