homelab:
  externalSecret:
    enabled: false

  customIngressRoutes:
    enabled: true

  argocdIngressRoute:
    enabled: true
    host: argocd.skippythesnake.com

  certManagerTls:
    enabled: true
    certificateName: skippythesnake
    secretName: skippythesnake-tls
    issuerRef:
      name: letsencrypt-production
      kind: ClusterIssuer
    commonName: "*.skippythesnake.com"
    dnsNames:
      - "*.skippythesnake.com"
      - skippythesnake.com

traefik:
  additionalArguments:
    - "--serversTransport.insecureSkipVerify=true"

  service:
    spec:
      loadBalancerIP: "10.128.20.60"

  ingressRoute:
    dashboard:
      matchRule: Host(`traefik.skippythesnake.com`)
