apiVersion: apps/v1
kind: Deployment
metadata:
  name: seerr
  labels:
    app: seerr
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: seerr
  template:
    metadata:
      labels:
        app: seerr
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      tolerations:
        - key: node.kubernetes.io/unreachable
          effect: NoExecute
          tolerationSeconds: 10
      containers:
        - name: seerr
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /api/v1/settings/public
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /api/v1/settings/public
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 3
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: seerr-config
          {{- else }}
          emptyDir: {}
          {{- end }}
