version: "3.8"

services:
  telegraf:
    image: telegraf
    container_name: telegraf
    volumes:
      - /mnt/user/appdata/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/utmp:/var/run/utmp:ro
      - /run/udev:/run/udev:ro
      - /sys:/rootfs/sys:ro
      - /etc:/rootfs/etc:ro
      - /proc:/rootfs/proc:ro
    environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs
    depends_on:
      - influxdb

  influxdb:
    image: influxdb
    container_name: influxdb
    volumes:
      - /mnt/user/appdata/influxdb2:/var/lib/influxdb2
    ports:
      - 8086:8086
