services:
  "{{ service_name }}":
    image: tailscale/tailscale:latest
    container_name: "{{service_name}}"
    hostname: "{{hostname}}"
    network_mode: host
    environment:
      # - TS_AUTHKEY=
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_AUTH_ONCE=true
      - "TS_ROUTES={{ subnet }}"
    volumes:
      - "{{ (appdata_path, service_name) | path_join }}:/var/lib/tailscale"
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
