- name: Create data directories
  vars:
    service_name: "promtail"
    data_directories:
      - "{{ service_name }}"
  ansible.builtin.import_role:
    name: docker-deploy
    tasks_from: create-container
