apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: fern
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`fern.skippythesnake.com`)
      kind: Rule
      middlewares:
        - name: default-headers
          namespace: traefik
      services:
        - name: fern-server
          port: 80
          scheme: http

---
apiVersion: v1
kind: Service
metadata:
  name: fern
  namespace: traefik
spec:
  ports:
    - protocol: TCP
      name: webui
      port: 80
      targetPort: 80
      type: ExternalName
      externalName: fern.lan
