- name: Create data directories
  vars:
    service_name: "downloads"
    data_directories:
      - "qbittorrent"
      - "jackett"
      - "sonarr"
      - "radarr"
  ansible.builtin.import_role:
    name: docker-deploy
    tasks_from: create-container
