external-secrets:
  installCRDs: true
  bitwarden-sdk-server:
    enabled: false

homelab:
  clusterSecretStore:
    enabled: true
    name: vault-homelab
  vault:
    server: http://fern.internal:8200
    path: secret
    version: v2
    auth:
      mountPath: approle
    authSecretName: vault-approle-eso
    caBundle: ""
  vaultAppRoleSealedSecret:
    enabled: true
    encryptedData:
      role-id: AgBYhqw6M5tMKhJEE2ZgVhS2ihQ6UXWCRati6oOsS7nW3n5DF2FaYnHNHwjxxzm62NWD1vncGOfDd1suWA/mgCuELSYl48Qd7HPM1kj8yWFleP0aXe4QGnk/Zlc//0xWChjnMka7JBg5/MXLpfxAa0WyTXG6Ibyetu2sEGVmz0E9w3kHJikdgXoNSgZclCZ7gCUhQslCOOFl48p1cPiE/+CDUuAiAvZpk9ZxEr+jGPnRAwqNV+oQVDNcvUhiITzjUVyfK3qCbhcHsUrMc2OfiA8SLm6Y73pO/mH1LxBMxY9rEXYTpEGoaV9Z55X2fXotLfl7C0cYKm8Kj2amgHQbfh/2NRueLIa4lEXtb8CchmEfKpGoryL9Tt7t8WUDcMUUY4XXVUz+QRU/vUOxC0CxJ17aLRxkVnLBjS5Dm18L8TeDAZ472zH/8ZUhV5Av8OCUhUU6VV2jHceh4K4smik41N3gjUbQz+JaOiTFlcBGkFz2qf2Kji2EmuRVrFJChWehC+dZengKU6jxi1b7Y7w09tZ1hlQTmLnvkeVeNT8Cl90h4acFTCgY7+v6OVAGFlLOeERAOGf7yazhyAMhehS7naVRUgofhJclz9gYMpR+kJca1cWYrCxAxIt97QWD4AaKI1uBTYKP+/35Nnlp0UH+QKvegLStKDAJxmPXCzeA1M1SBVNV8gX0p2IjUYFMhBiqpIH4zWdnf3EuSl3fuiw9vS3m/RqUK1szsaSn5XfBhcMsLrEJHag=
      secret-id: AgAmsLzMDbA8iodCi+IVnrji1/G883XixR1lpPpJ963JYLjcuphxWxUzJRDvmYgDl66cq1CUiWYd8y4L2HfAVKa/PbQPdmKBJWs4EEVWY0yIDyl4K/CQ0tNytElT3EIEJyAOXppz4NN3zHyeSO8JkJniuPDClWQoTFo3/JmGptyk4U9PRICJKJUbXilzuT6Mi8KyLe2psLdT3PGukzSMMNR0YH+cEFn9+CawwYvmtTEVuE0ZNTfcu+OtqEKCtT/GGRdPH0/oD2jjEnJXDBzXFo6b9pLbFxI9YtcXBPUMAhNqc6IygsxTLv2hP1kJcvr1QUg05yaJ5NojLCvwta3qUYURJSXij2/0JBFRAEEhK16mgvumqlG1OEvawPMlvLC0lpTnKW7sRYYE/KxR+FypF/3GNzuc5RCPpWetbmO9JMt6pmKqpP6ojpGrMN3GjTNKb1lP0ROKO04jBiBqHMT8m0MFeQocJCPq+r8vDEvHBQWVcLMdTf2FlHpqkoC16yO3752Czix/uBjoVCiTfbQENrQm7ZzC9r+2ZIwiSlxDfsKwaxEyEMGCWjo38vqg67Xt0w9nP2dui3lYDcmMBFgwXDQuq1IC7XsD93f3vVbsgXI+NLbj/QLJ4TVhBEcxtK/TpYsW/OVh5LkMsPR3cbggkxGtuzTa2EJpLfl32Wk2g5eQVG047tIqh4cA/nlBmkO/MdCnNqv8DgaUVumxaEQyDgbEIR9AP81KKJvQR5SYTFHq/fDnW8g=
