external-secrets:
  installCRDs: true
  bitwarden-sdk-server:
    enabled: false

homelab:
  clusterSecretStore:
    enabled: true
    name: vault-homelab
  vault:
    server: http://fern.internal:8200
    path: secret
    version: v2
    auth:
      mountPath: approle
    authSecretName: vault-approle-eso
    caBundle: ""
  vaultAppRoleSealedSecret:
    enabled: true
    encryptedData:
      role-id: AgBP5zy0JutKMracltpC16ipuE56j0oZC2HrASQVxiYGGAm3rVWtOQn4jaD/FbD+qwK2WOXotg/o8CY4vIaSn9VTJkmbdYTbqDC6A6V7L/iXEMV7WTF5/O4/+4f5h+X4UfWPxmhHk0rbyEIVHAgiicvfqCf9phnOB0BkCZHHkvg250ByCx6gmlpnGgZ2wHG7zkJ/5mAbNWeRvYa3z8c/DTJrkkDM6YjXGCElA2LMjJeu/6hyKEQSVvHA4iTmosJFULmnz0PKAMmndQS8GGId3E7EkUTSrR6k7nyy7nx8I915O/+0K+Jrv2x3KX0O+527xjaO3082OH6NKaYwb5DhMr2E8B1em609h3YoUa6keks/ga9uUdiwHGlxTX7Gstl0vfQ4DYky2bHQPrQOQo+2GdUE5EenssqBI/Lm60Tg4i70Pz4LVhsp7snS7hN3v/gKcECBHKvTnxke9pFspI9zay4fm2JgUcVJDl5bgqg6MsyTQJ4l3cx+RG4FJZdfhMGcWUx6pI3dL2mYSzw/6208BAIaSy0+8yiD2DSzCnyyJaHaf2roMRQKKCN2FGFfNEVUNhTm4qh+lVzqde9Et4G1wM6uEdfHQAf2TJZtm4Ph1vSj/j6KAI9xSLajMQAvqGdFAMWudleVYUV9nyFcjoQgFEqpiO0IKjT3Os+9hM2L/AwxJu05z8WdeXzyjH5m0TDFddYG8Dr2YYURqmrxQx4NjqU08ibzAQ5fa0IbZZfsS/s15yeBU7Y=
      secret-id: AgBRaRsuxEGOlpqzKkFj4z03/9CzTqc3y7nLt8p1LF8mLPrbkyUd+MXyVL+VTc8SgPGhDi7e4S6WK9VSD2r1ABFfrTijzbJOEK/enmB9FQEUXMKdI6fshZDHx1OqsXE1+U3dNb42eVBNLZ8Vse7+3Fmn47xZx7Lw8ZbGuxqWHbM1XOx1WezOLtVlPOJ8KQ6uOPTq4+CvAy+C6qIVMN26Ts9Lm6MdEXrkceD30mztwkZrReq5MbBX3m3c2er0IbMTGLEY2SLGffuuASXiWvYMA4cqiYx2tQ4BMNZ2MvhIp3Jgk6OtXZG1KIBxhBD8APADyk4vFZtJwedBO2my1TsUM+wrjv1lGqgR3oGjVqpyOA2ki/I6bmUDc28kSArxyXLzLzCw8+G2b02ZmI47NvUSkOYdXIq/YWRX1f6fl/3ZmfDrlbpRhnWi99RvxVg9igUVYxTP+lNwSWkKoKWmgQP6pfzniUKX6TUwOtyBX255b05pwADnW8dy69TlwtiB1Y9ZhEyXFYEprvrFoWzsXuIq1EjGzqKm2lv3Lc8oaZc+TkyoapRXvRYD+TIJbVHrS77Ys0e9tORsSdL2YYKOVMAYUbraB0DiIibqx7Wp1EXd42CNsU+W3j8qVRkH8JJzE5WLKa3M+Wu9n6QpCQ/SvgWMFVr37TtGginyPQPeI6KggCF4cIiWxsGNFSkiG+IojsEcEU+BAv520E+OVNkY03uBCMueZvjQZLEOL4wHnoUG8Zjub6+N94g=
