apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  labels:
    app: homeassistant
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      tolerations:
        - key: node.kubernetes.io/unreachable
          effect: NoExecute
          tolerationSeconds: 10
      containers:
        - name: homeassistant
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: TZ
              value: {{ .Values.env.tz | quote }}
          ports:
            - containerPort: 8123
          readinessProbe:
            httpGet:
              path: /
              port: 8123
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8123
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: homeassistant-config
          {{- else }}
          emptyDir: {}
          {{- end }}
