{{- if .Values.persistence.enabled }}
{{- include "common.persistentStorage" (dict "pvcName" "homeassistant-config" "pvName" (printf "%s-homeassistant-config" .Release.Namespace) "size" .Values.persistence.size "storageClass" .Values.persistence.config.storageClass "nfs" .Values.persistence.config.nfs) }}
{{- end }}
