apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/ReidMason/homelab.git
        revision: main
        files:
          - path: "kubernetes-v2/values/dev/*/deploy.yaml"
  template:
    metadata:
      name: '{{ index .path.segments 3 }}'
      namespace: argocd
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ index .path.segments 3 }}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/ReidMason/homelab.git
        targetRevision: main
        path: 'kubernetes-v2/charts/{{ .chart }}'
        helm:
          releaseName: '{{ index .path.segments 3 }}'
          valueFiles:
            - values.yaml
            - ../../values/dev/{{ index .path.segments 3 }}/values.yaml
