{{- if .Values.persistence.enabled }}
{{ include "common.persistentStorage" (dict "pvcName" "qbittorrent-config" "size" .Values.persistence.size "storageClass" .Values.persistence.qbittorrentConfig.storageClass) }}
---
{{ include "common.persistentStorage" (dict "pvcName" "prowlarr-config" "size" .Values.persistence.size "storageClass" .Values.persistence.prowlarrConfig.storageClass) }}
{{- end }}
