apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
spec:
  selector:
    app: qbittorrent
  ports:
    - name: qbittorrent
      protocol: TCP
      port: {{ .Values.ports.qbittorrent }}
      targetPort: {{ .Values.ports.qbittorrent }}
    - name: prowlarr
      protocol: TCP
      port: {{ .Values.ports.prowlarr }}
      targetPort: {{ .Values.ports.prowlarr }}
    - name: flaresolverr
      protocol: TCP
      port: {{ .Values.ports.flaresolverr }}
      targetPort: {{ .Values.ports.flaresolverr }}
{{- if .Values.homelab.lanService.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-lan
  {{- if .Values.homelab.lanService.metallbAddressPool }}
  annotations:
    metallb.io/address-pool: {{ .Values.homelab.lanService.metallbAddressPool | quote }}
  {{- end }}
spec:
  type: {{ .Values.homelab.lanService.type }}
  {{- if .Values.homelab.lanService.loadBalancerIP }}
  loadBalancerIP: {{ .Values.homelab.lanService.loadBalancerIP | quote }}
  {{- end }}
  selector:
    app: qbittorrent
  ports:
    - name: qbittorrent
      protocol: TCP
      port: {{ .Values.ports.qbittorrent }}
      targetPort: {{ .Values.ports.qbittorrent }}
    - name: prowlarr
      protocol: TCP
      port: {{ .Values.ports.prowlarr }}
      targetPort: {{ .Values.ports.prowlarr }}
{{- end }}
