version: "3.8"

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    restart: always
    ports:
      - 32400:32400/tcp # Webui
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - "{{ (appdata_path, 'PlexMediaServer') | path_join }}:/config"
      - /tmp/:/transcode
      - "{{ plex_path }}:/data"
    environment:
      - "TZ=Europe/London"
      - "PLEX_CLAIM={{ plex_claim }}"
      # - "ADVERTISE_IP=http://<hostIPAddress>:32400/"
      - "USER_ID=99"
      - "GROUP_ID=100"
      - "UMASK=000"
    hostname: "{{ hostname }} Plex"
