services:
  "{{ service_name}}":
    container_name: "{{ service_name }}"
    image: grafana/grafana:11.2.2
    restart: always
    volumes:
      - "{{ (appdata_path, service_name) | path_join }}:/var/lib/grafana"
    user: "1000:1000"
    networks:
      - skippynet

networks:
  skippynet:
    external: true
