apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: postgresql
spec:
  entryPoints:
    - postgresql
  routes:
    - match: HostSNI(`*`)
      kind: Rule
      services:
        - name: postgresql
          port: 5432
