apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: postgresql
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`postgresql.skippythesnake.com`)
      kind: Rule
      services:
        - name: postgresql
          port: 5432
  tls:
    passthrough: true
