apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: "admin-password"
      remoteRef:
        key: "secrets/postgres"
        property: "admin-password"
    - secretKey: "admin-username"
      remoteRef:
        key: "secrets/postgres"
        property: "admin-username"
