apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: traefik
  namespace: metallb-system
spec:
  addresses:
    - 10.128.0.70/32
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pihole
  namespace: metallb-system
spec:
  addresses:
    - 10.128.0.72/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement-config
  namespace: metallb-system
spec:
  ipAddressPools:
    - traefik
    - portainer-agent
    - pihole
