apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.128.0.70 # Traefik
    - 10.128.0.71 # Portainer agent
    - 10.128.0.72 # Pihole
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement-config
  namespace: metallb-system
spec:
  ipAddressPools:
    - first-pool
