- name: "{{ service_name }} | Create data directories"
  become: true
  ansible.builtin.file:
    path: "{{ (appdata_path, item) | path_join }}"
    owner: "{{ uid }}"
    group: "{{ gid }}"
    state: directory
    mode: "0775"
  loop: "{{ data_directories }}"

- name: "{{ service_name }} | Create Docker compose directory"
  ansible.builtin.file:
    path: "{{ (compose_files_dest, service_name) | path_join }}"
    state: directory
    mode: "0775"

- name: "{{ service_name }} | Copy compose files"
  ansible.builtin.template:
    src: "templates/docker-compose.yaml"
    dest: "{{ (compose_files_dest, service_name, 'docker-compose.yaml') | path_join }}"
    mode: "0775"

- name: "{{ service_name }} | Create Docker container"
  community.docker.docker_compose_v2:
    project_src: "{{ (compose_files_dest, service_name) | path_join }}"
