- name: Create docker network
  community.docker.docker_network:
    name: skippynet

- name: Create appdata directory
  ansible.builtin.file:
    path: "{{ appdata_path }}"
    state: directory
    mode: "0775"

- name: Create Docker compose directory
  ansible.builtin.file:
    path: "{{ compose_files_dest | path_join }}"
    state: directory
    mode: "0775"
