- name: Create appdata directory
  become: true
  ansible.builtin.file:
    path: "{{ appdata_path }}"
    state: directory
    owner: "{{ uid }}"
    group: "{{ gid }}"
    mode: "0775"

- name: Create Docker compose directory
  ansible.builtin.file:
    path: "{{ compose_files_dest | path_join }}"
    state: directory
    mode: "0775"
