version: "3.8"

services:
  pi-hole:
    container_name: pi-hole
    image: pihole/pihole:latest
    network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: "Europe/London"
      WEBPASSWORD: "{{ pihole_webpassword }}"
    volumes:
      - "{{ (appdata_path, 'pihole') | path_join }}:/etc/pihole"
      - "{{ (appdata_path, 'pihole', 'dnsmasq.d') | path_join }}:/etc/dnsmasq.d"
    restart: always
