persistence:
  uid: "65534"
  gid: "65534"

homelab:
  dnsService:
    loadBalancerIP: 10.128.20.62
  externalSecret:
    remoteKey: secret/prod/pihole
  ingressRoute:
    enabled: true
    host: pihole-kube.skippythesnake.com
