- name: Disable SSH password auth
  ansible.builtin.lineinfile:
    dest: /etc/ssh/ssh_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  notify:
    - Restart SSH daemon
