- name: Setup Docker containers for apphost
  hosts: vera
  vars:
    home_path: "{{ ansible_env.HOME }}"
    appdata_path: "{{ (home_path, 'appdata') | path_join  }}"
    compose_files_dest: "{{ ( home_path, 'compose-files') | path_join }}"
  roles:
    - docker-deploy
    - nginx-proxy-manager
    - portainer-agent
    - plex-media-server
    - portainer
    - startpage
    - media
    - habit-tracker
    - tailscale
    - node-exporter
    - prometheus
    - loki
    - promtail
    - grafana
    - hashicorp-vault
