- name: Setup Docker containers for apphost
  hosts: vera-v2
  vars:
    home_path: "{{ ansible_env.HOME }}"
    appdata_path: "{{ (home_path, 'appdata') | path_join  }}"
    compose_files_dest: "{{ ( home_path, 'compose-files') | path_join }}"
  roles:
    - docker-deploy
    - docker-deploy/nginx-proxy-manager
    - docker-deploy/portainer-agent
    - docker-deploy/plex-media-server
    - docker-deploy/portainer
    - docker-deploy/startpage
