- name: Setup Docker containers for apphost
  hosts: vera
  vars:
    home_path: "{{ ansible_env.HOME }}"
    appdata_path: "{{ (home_path, 'appdata') | path_join  }}"
    compose_files_dest: "{{ ( home_path, 'compose-files') | path_join }}"
    gid: "100"
    uid: "99"
  roles:
    - docker-deploy
    - docker-deploy/startpage
    - docker-deploy/portainer-agent
    - docker-deploy/portainer
    - docker-deploy/nginx-proxy-manager
    - docker-deploy/plex-media-server
    - docker-deploy/downloads
