- name: Setup Docker containers for apphost
  hosts: vera-v2
  vars:
    home_path: "{{ ansible_env.HOME }}"
    appdata_path: "{{ (home_path, 'appdata') | path_join  }}"
    compose_files_dest: "{{ ( home_path, 'compose-files') | path_join }}"
    gid: "1000"
    uid: "1000"
  roles:
    - docker-deploy
    - docker-deploy/portainer-agent
    - docker-deploy/plex-media-server
