---
- name: Initial setup
  hosts: testhost

  tasks:
    - name: Update packages
      become: true
      ansible.builtin.apt:
        update_cache: true
        upgrade: true

    # - name: Install essential packages
    #   ansible.builtin.package:
    #   name: "{{ packages }}"

    - name: Disable SSH password auth
      become: true
      ansible.builtin.lineinfile:
        dest: /etc/ssh/ssh_config
        regexp: "^#PasswordAuthentication yes"
        line: "PasswordAuthentication no"
      register: ssh_config

    - name: Restart SSH daemon
      become: true
      service:
        name: ssh
        state: restarted
      when: ssh_config.changed

    - name: Enable passwordless sudo for "{{ ansible_user_id }}"
      become: true
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        regexp: "^%wheel"
        line: "{{ ansible_user_id }} ALL=(ALL) NOPASSWD: ALL"
        validate: "/usr/sbin/visudo -cf %s"

    - name: Suppress login message (hushlogin)
      become: true
      ansible.builtin.file:
        path: ~/.hushlogin
        mode: "0644"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        modification_time: preserve
        access_time: preserve
        state: touch
