---
- name: Mount network shares
  hosts: vera

  tasks:
    - name: Install nfs common
      become: true
      ansible.builtin.package:
        name: nfs-common

    - name: Create mount points
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        mode: "0775"
      with_items: "{{ paths }}"

    - name: Mount network shares
      become: true
      ansible.posix.mount:
        src: "{{ item.src }}"
        path: "{{ item.path }}"
        opts: "{{ item.opts }}"
        state: mounted
        fstype: nfs
        boot: true
      with_items: "{{ paths }}"
