apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-issuer
spec:
  acme:
    email: maddogshain132@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory

    privateKeySecretRef:
      name: issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            email: maddogshain132@gmail.com
            apiKeySecretRef:
              name: cloudflare-api-key
              key: api-key
