services:
  "{{ service_name}}":
    container_name: "{{ service_name }}"
    image: grafana/loki:3.1.2
    restart: always
    volumes:
      - "{{ (appdata_path, service_name, 'data') | path_join }}:/loki"
      - "{{ (appdata_path, service_name, 'config') | path_join }}:/etc/loki"
    ports:
      - 3100:3100
    networks:
      - skippynet

networks:
  skippynet:
    external: true
