external-secrets:
  installCRDs: true
  bitwarden-sdk-server:
    enabled: false

homelab:
  clusterSecretStore:
    enabled: true
    name: vault-homelab
  vault:
    server: http://fern.internal:8200
    path: secret
    version: v2
    auth:
      mountPath: approle
    authSecretName: vault-approle-eso
    caBundle: ""
  vaultAppRoleSealedSecret:
    enabled: true
    encryptedData:
      role-id: AgAV8DnXlUFVYsMrabwG64lGl1C7ppYMpZZoAPI380VYVTF0/To5FUHf0Dc+EmAPVMYOJqq5VDGngQAhR4+NbglX3zMHy90brEyO269CoOB7aFIe5r1QPYK3GBZcDGmBsp/H3+Ps3VQhraBa9ht94zQRaXZ97nJUbGLZDMoeZBlNPZfg2EQZeyMnKQtZveTYbMiRcow40efegxpemxSA4q/SnxENqeuRbNBQzZWqrGgPJjbw1o/XjRanYZyikEg9YS9RkgQF8xjpEPyfUS/XYioaBne/lzZPEzMhUfibxSRj4dCNC+BJXF+Kb44yN0siX8tghwi+CpZakTYqaUnD1aW3CKZ2FHwE64g1J6OE2oaU/13FRjXilXE0q6RSQyLy5jyZZsudZq8VkvFFBPlIoCrVUhuVqZMRE2Z2PiM24tu3D/I6bJqKoh8PdfSl9EN8skWrZ9wSme+OC22y+nXeL7NHxPqd9YDmZl8nE2hqGmgV5A//4/u4NpMpa1SYCpCMuor/eUkUKchTABiKA76I7C0fDpNZfkXzhoGtlm09trSZ7KM2xQ26rWwjv/TThNVbops74LEO9DEB0PZQqSz0XLVSUB7uY1s2ujnHvj9t6hJ2m/sW4deCucLoojKjRuyd5J7PPm00RxF1UknMxSsVsL8iZxycN63JXoFNyGZzcWkFNsWUGmP9ZLpoqeLs42DqjdazkK9zybJXWQ1ZpeGm8kuXLUuVDRMjiBUiksgUdAQgRt57Uik=
      secret-id: AgAz+wX5NuqBs2JLzlucQSWqecU7r2x8DxVTFDD0oW851jNerVBOS9eAYC8TaDXG+hftx1GBT72TCjzH6JBYrSw8qhumWVuu7pusiLL7kNKI6/8D1qSY0UFafDn0qDxYT2lkOBfSXx5V9OgprbN9awZoVADvrU56Y3tVIBM+x1SKPhBT0o19MIUhwhwVL0d5+90aXZULxsEOl9klji3TkeeTPtSnDwQhcT4tVGhp8hYbTKpCEOGWCHLbeyY2E/W2qXZ+hR3CDugLYE9WhzOhlZVgii6RzoIMsVKWx61bQ6h075/x2cT/5Gd42fqfxmdrBBtFVMUvwnnzbU+y2ypgUNoem/0vaK2CinknqUeK1ZeILm0e76yXC3tPChkl8BA21MrbKmKDOrP2RlAj3ZNHq9OP+1zTmO9Ta4TL+9OjSaD+8vUjjYfka+3IMtmP18bxONTZBuWAqBrHRK46Z2fNABMTbadO2d/rwGW+TVn6fB5zOcv2Qwa1U94Vadwf+Agug8Vdi4flSaWT9hDOu2lqeq+ENd15nz8WapYVjns2hQIGzJk/Wsk8NUQf+4XGQTKeymNT90E/okjNybfzbG4ULyM13+/LJxkBcQfDORWwwwbdkwcpSnv4iF5GMuJ65QSsVnxlOmZ4clX98leEsqDDGpvkN70gGn74KqmEZV0Zi9HxRG04wHZC7+mn/UrQ8DkwIbbkpn5CHlwwWVjCnIi2k+RWhU57b1b9siTjcQKBBKcscwujfJc=
