apiVersion: v2
name: sealed-secrets-bootstrap
description: Sealed Secrets controller (Helm wrapper around Bitnami chart)
type: application
version: 0.1.0
dependencies:
  - name: sealed-secrets
    version: 2.18.5
    repository: https://bitnami-labs.github.io/sealed-secrets
