jellyfin:
  persistence:
    config:
      storageClass: longhorn
  volumes:
    - name: library
      nfs:
        server: fern.internal
        path: /mnt/user/Plex
  volumeMounts:
    - name: library
      mountPath: /library
      readOnly: true

homelab:
  ingressRoute:
    enabled: true
    host: jellyfin.skippythesnake.com
