{{- if .Values.persistence.enabled }}
{{- include "common.persistentStorage" (dict "pvcName" "matter-server-data" "pvName" (printf "%s-matter-server-data" .Release.Namespace) "size" .Values.persistence.size "storageClass" .Values.persistence.data.storageClass "nfs" .Values.persistence.data.nfs) }}
{{- end }}
