apiVersion: v1
kind: Service
metadata:
  name: matter-server
spec:
  selector:
    app: matter-server
  ports:
    - name: ws
      protocol: TCP
      port: 5580
      targetPort: 5580
{{- if .Values.homelab.lanService.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: matter-server-lan
  {{- if .Values.homelab.lanService.metallbAddressPool }}
  annotations:
    metallb.io/address-pool: {{ .Values.homelab.lanService.metallbAddressPool | quote }}
  {{- end }}
spec:
  type: {{ .Values.homelab.lanService.type }}
  {{- if .Values.homelab.lanService.loadBalancerIP }}
  loadBalancerIP: {{ .Values.homelab.lanService.loadBalancerIP | quote }}
  {{- end }}
  selector:
    app: matter-server
  ports:
    - name: ws
      protocol: TCP
      port: 5580
      targetPort: 5580
{{- end }}
