{{- if .Values.persistence.enabled }}
{{- include "common.persistentStorage" (dict "pvName" (printf "%s-portainer-data" .Release.Namespace) "pvcName" "portainer-data" "size" .Values.persistence.size "nfs" .Values.persistence.nfs) }}
{{- end }}
