services:
  "{{ service_name}}":
    container_name: "{{ service_name }}"
    image: pihole/pihole:2024.07.0
    restart: always
    network_mode: "host"
    hostname: "{{ hostname }}"
    # ports:
    #   - "53:53/tcp"
    #   - "53:53/udp"
    #   - "80:80/tcp"
    environment:
      TZ: "Europe/London"
    volumes:
      - "{{ (appdata_path, service_name, 'data') | path_join }}:/etc/pihole"
      - "{{ (appdata_path, service_name, 'dnsmasq') | path_join }}:/etc/dnsmasq.d"
