services:
  "{{ service_name}}":
    container_name: "{{ service_name }}"
    image: grafana/promtail:3.1.2
    restart: always
    volumes:
      - "{{ (appdata_path, service_name) | path_join }}:/mnt/config"
      - "/var/log:/mnt/log:ro"
    command: -config.file=/mnt/config/config.yaml
    networks:
      - skippynet

networks:
  skippynet:
    external: true
