{{- if .Values.homelab.customIngressRoutes.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: sonarr-theme
  namespace: {{ .Release.Namespace }}
spec:
  plugin:
    themepark:
      app: sonarr
      theme: nord
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: qbittorrent-theme
  namespace: {{ .Release.Namespace }}
spec:
  plugin:
    themepark:
      app: qbittorrent
      theme: nord
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: jackett-theme
  namespace: {{ .Release.Namespace }}
spec:
  plugin:
    themepark:
      app: jackett
      theme: nord
{{- end }}
