{{- if .Values.homelab.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.homelab.externalSecret.name | quote }}
spec:
  refreshInterval: {{ .Values.homelab.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.homelab.externalSecret.clusterSecretStoreName | quote }}
  target:
    name: {{ .Values.homelab.externalSecret.name | quote }}
    creationPolicy: Owner
  data:
    - secretKey: CF_DNS_API_TOKEN
      remoteRef:
        key: {{ .Values.homelab.externalSecret.remoteKey | quote }}
        property: {{ .Values.homelab.externalSecret.property | quote }}
{{- end }}
