services:
  "{{ service_name }}":
    container_name: "{{ service_name }}"
    image: ghcr.io/reidmason/plex-autoscan:latest
    restart: always
    ports:
      - 3030:3030
    volumes:
      - "{{ (appdata_path, service_name) | path_join }}:/data"
