appdata_path: "~/appdata"
username: reid

packages:
  - neofetch
  - speedtest-cli
  - docker-compose

dockers:
  - uptime-kuma
  - portainer-agent
  - node-exporter

docker_install_compose: true
pip_install_packages:
  - name: docker
