apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: paperless-secret
    creationPolicy: Owner
  data:
    - secretKey: "database-url"
      remoteRef:
        key: "secrets/paperless"
        property: "database-url"
