replicaCount: 1

image:
  repository: ghcr.io/reidmason/habit-tracker
  tag: "0.3.4"

service:
  port: 80
  targetPort: 8000

persistence:
  enabled: true
  size: 1Gi
  nfs:
    server: ""
    path: ""

homelab:
  ingressRoute:
    enabled: false
    host: ""
    entryPoints:
      - websecure
    servicePort: 80
