services:
  "{{ service_name}}":
    container_name: "{{ service_name }}"
    image: vault:1.13.3
    restart: always
    volumes:
      - "{{ (appdata_path, service_name, 'data') | path_join }}:/vault/file"
    cap_add:
      - IPC_LOCK
    networks:
      - skippynet

networks:
  skippynet:
    external: true
