services:
  "{{ service_name}}":
    container_name: "{{ service_name }}"
    image: vault:1.19
    restart: always
    ports:
      - "8200:8200"
    volumes:
      - "{{ (appdata_path, service_name, 'data') | path_join }}:/vault/data"
      - "{{ (appdata_path, service_name, 'config.hcl') | path_join }}:/vault/config.hcl"
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config.hcl
    networks:
      - skippynet

networks:
  skippynet:
    external: true
