image:
  repository: pihole/pihole
  tag: "2024.07.0"

persistence:
  enabled: true
  size: 10Gi
  nfs:
    server: fern.internal
    path: /mnt/user/kubernetes/pihole
  volumeMounts:
    - mountPath: /etc/pihole
      subPath: data
    - mountPath: /etc/dnsmasq.d
      subPath: dnsmasq.d
  uid: "1000"
  gid: "100"
  fixPermissions: true

env:
  tz: Europe/London

homelab:
  externalSecret:
    enabled: true
    name: pihole-secret
    refreshInterval: 15s
    clusterSecretStoreName: vault-homelab
    remoteKey: ""
    property: webui-password
    secretKey: webui-password
  dnsService:
    type: LoadBalancer
    externalTrafficPolicy: Local
    metallbAddressPool: default-pool
  ingressRoute:
    enabled: false
    host: ""
    entryPoints:
      - websecure
    servicePort: 80
