- name: Ensure appdata directory exists
  ansible.builtin.file:
    path: "{{ appdata_path }}"
    state: directory
    mode: "0775"

- name: Ensure Docker compose dir exists
  ansible.builtin.file:
    path: "{{ (compose_files_dest, item) | path_join }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0775"
  loop: "{{ dockers }}"

- name: Copy compose files
  ansible.builtin.template:
    src: "{{ (compose_files_src, item, 'docker-compose.yml') | path_join }}"
    dest: "{{ (compose_files_dest, item, 'docker-compose.yml') | path_join }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0775"
  loop: "{{ dockers }}"

- name: Create Docker containers
  community.docker.docker_compose:
    project_src: "{{ (compose_files_dest, item) | path_join }}"
  loop: "{{ dockers }}"
