---
- hosts: rpi
  become: yes

  pre_tasks:
    # This is required to install Docker and pip packages
    - name: Delete Python EXTERNALLY-MANAGED
      ansible.builtin.file:
        path: /usr/lib/python3.11/EXTERNALLY-MANAGED
        state: absent

  roles:
    - role: system
    - role: geerlingguy.pip
    - role: geerlingguy.docker

  tasks:
    # Docker_compose on Ansible is really messed up so we need to downgrade
    # https://github.com/docker/docker-py/issues/3194
    - name: Downgrade python Docker
      ansible.builtin.pip:
        name: docker==6.1.3

    - name: Adding user to docker group
      ansible.builtin.user:
        name: "{{ username }}"
        group: "{{ username }}"
        shell: /bin/bash
        groups: docker
        append: true
