services:
  "{{ service_name}}":
    container_name: "{{ service_name }}"
    image: ghcr.io/reidmason/habit-tracker:0.2.1
    restart: always
    volumes:
      - "{{ (appdata_path, service_name) | path_join }}:/app/data"
    networks:
      - skippynet

networks:
  skippynet:
    external: true
