replicaCount: 1

image:
  repository: ghcr.io/reidmason/relay-ingest
  tag: "edge"

env:
  natsUrl: nats://nats.nats.svc.cluster.local:4222
  port: "8080"

service:
  port: 8080

homelab:
  ingressRoute:
    enabled: false
    host: ""
    entryPoints:
      - websecure
    servicePort: 8080
  lanService:
    enabled: false
    type: LoadBalancer
    loadBalancerIP: ""
    metallbAddressPool: default-pool
