persistence:
  nfs:
    server: fern.internal
    path: /mnt/user/kubernetes/authentik

homelab:
  externalSecret:
    remoteKey: "secret/prod/authentik"
  ingressRoute:
    enabled: true
    host: auth.skippythesnake.com
