longhorn:
  preUpgradeChecker:
    jobEnabled: false
    upgradeVersionCheck: false
  persistence:
    defaultClass: true
    defaultClassReplicaCount: 3
    recurringJobSelector:
      enable: false
      jobList: ""
  defaultSettings:
    defaultReplicaCount: "3"
    defaultDataPath: /var/lib/longhorn
  defaultBackupStore:
    backupTarget: ~
    backupTargetCredentialSecret: ~
    pollInterval: ~
  longhornUI:
    replicas: 2
  ingress:
    enabled: false

homelab:
  ingressRoute:
    enabled: false
    host: ""
    entryPoints:
      - websecure
    servicePort: 80
  backup:
    enabled: false
    daily:
      cron: "0 2 * * *"
      retain: 7
    weekly:
      cron: "0 3 * * 0"
      retain: 4
  trim:
    enabled: false
    cron: "0 4 * * 0"
  metrics:
    enabled: false
