services:
  smartctl-exporter:
    container_name: smartctl-exporter
    image: prometheuscommunity/smartctl-exporter:latest
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - 9633:9633
