promtail:
  config:
    clients:
      - url: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push
    snippets:
      extraScrapeConfigs: |
        - job_name: syslog
          syslog:
            listen_address: 0.0.0.0:1514
            listen_protocol: tcp
            labels:
              job: syslog
          relabel_configs:
            - source_labels: [__syslog_message_hostname]
              target_label: host

  extraPorts:
    syslog:
      name: tcp-syslog
      containerPort: 1514
      protocol: TCP
      service:
        type: LoadBalancer
        port: 1514
        loadBalancerIP: 10.128.20.66

  # Exposes the metrics port so kube-prometheus-stack can scrape it
  service:
    enabled: true

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
