homelab:
  externalSecret:
    enabled: false
    name: cloudflare-dns-api-token
    refreshInterval: 1h
    clusterSecretStoreName: vault-homelab
    remoteKey: secret/data/homelab/traefik/cloudflare
    property: token

  argocdIngressRoute:
    enabled: false
    host: ""
    entryPoints:
      - websecure
    serviceName: argocd-server
    serviceNamespace: argocd
    servicePort: 443

traefik:
  additionalArguments:
    - "--serversTransport.insecureSkipVerify=true"

  persistence:
    enabled: true
    size: 256Mi
    accessMode: ReadWriteOnce

  podSecurityContext:
    fsGroup: 65532
    fsGroupChangePolicy: OnRootMismatch

  deployment:
    initContainers:
      - name: acme-json-perms
        image: docker.io/library/busybox:1.36
        command:
          - sh
          - -c
          - |
            touch /data/acme.json
            chmod 600 /data/acme.json
            chown 65532:65532 /data/acme.json
        volumeMounts:
          - name: data
            mountPath: /data

  certificatesResolvers:
    letsencrypt:
      acme:
        email: ssl@skippythesnake.com
        caServer: https://acme-staging-v02.api.letsencrypt.org/directory
        storage: /data/acme.json
        dnsChallenge:
          provider: cloudflare
          resolvers:
            - "1.1.1.1:53"
            - "1.0.0.1:53"

  envFrom:
    - secretRef:
        name: cloudflare-dns-api-token

  ports:
    websecure:
      http:
        tls:
          certResolver: letsencrypt

  ingressRoute:
    dashboard:
      enabled: true
      entryPoints:
        - websecure

  providers:
    kubernetesCRD:
      enabled: true
      allowExternalNameServices: true
      allowCrossNamespace: true
    kubernetesIngress:
      enabled: true
      allowExternalNameServices: true
      publishedService:
        enabled: false

  service:
    enabled: true
    type: LoadBalancer
    spec:
      externalTrafficPolicy: Local

  experimental:
    plugins:
      themepark:
        moduleName: "github.com/packruler/traefik-themepark"
        version: "v1.4.2"
