homelab:
  externalSecret:
    enabled: false
    name: cloudflare-dns-api-token
    refreshInterval: 1h
    clusterSecretStoreName: vault-homelab
    remoteKey: secret/data/homelab/traefik/cloudflare
    property: token

  argocdIngressRoute:
    enabled: false
    host: ""
    entryPoints:
      - websecure
    serviceName: argocd-server
    serviceNamespace: argocd
    servicePort: 443

  customIngressRoutes:
    enabled: false

  certManagerTls:
    enabled: false
    certificateName: wildcard-tls
    secretName: ""
    issuerRef:
      name: letsencrypt-staging
      kind: ClusterIssuer
    commonName: ""
    dnsNames: []

traefik:
  additionalArguments:
    - "--serversTransport.insecureSkipVerify=true"

  podSecurityContext:
    fsGroup: 65532
    fsGroupChangePolicy: OnRootMismatch

  ports:
    websecure:
      http:
        tls:
          enabled: true

  ingressRoute:
    dashboard:
      enabled: true
      entryPoints:
        - websecure

  providers:
    kubernetesCRD:
      enabled: true
      allowExternalNameServices: true
      allowCrossNamespace: true
    kubernetesIngress:
      enabled: true
      allowExternalNameServices: true
      publishedService:
        enabled: false

  service:
    enabled: true
    type: LoadBalancer
    spec:
      externalTrafficPolicy: Local

  experimental:
    plugins:
      themepark:
        moduleName: "github.com/packruler/traefik-themepark"
        version: "v1.4.2"
