{{- include "common.externalSecret" (dict
  "name" .Values.homelab.cloudflare.externalSecret.name
  "remoteKey" .Values.homelab.cloudflare.externalSecret.remoteKey
  "refreshInterval" .Values.homelab.cloudflare.externalSecret.refreshInterval
  "clusterSecretStoreName" .Values.homelab.cloudflare.externalSecret.clusterSecretStoreName
  "enabled" .Values.homelab.cloudflare.externalSecret.enabled
  "secretEnv" (list (dict "secretKey" .Values.homelab.cloudflare.externalSecret.secretKey "property" .Values.homelab.cloudflare.externalSecret.property))
) }}
