{{- if and .Values.homelab.cloudflare.externalSecret.enabled .Values.homelab.cloudflare.externalSecret.remoteKey }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cf-cloudflare-token
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.homelab.cloudflare.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.homelab.cloudflare.externalSecret.clusterSecretStoreName | quote }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.homelab.cloudflare.externalSecret.name | quote }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.homelab.cloudflare.externalSecret.secretKey | quote }}
      remoteRef:
        key: {{ .Values.homelab.cloudflare.externalSecret.remoteKey | quote }}
        property: {{ .Values.homelab.cloudflare.externalSecret.property | quote }}
{{- end }}
