{{- if .Values.homelab.clusterIssuers.production.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.homelab.clusterIssuers.production.name | quote }}
spec:
  acme:
    server: {{ .Values.homelab.clusterIssuers.production.acmeServer | quote }}
    email: {{ .Values.homelab.acme.email | quote }}
    privateKeySecretRef:
      name: {{ .Values.homelab.clusterIssuers.production.privateKeySecretRef | quote }}
    solvers:
      - dns01:
          cloudflare:
            email: {{ .Values.homelab.acme.cloudflare.dnsChallengeEmail | quote }}
            apiTokenSecretRef:
              name: {{ .Values.homelab.cloudflare.externalSecret.name | quote }}
              key: {{ .Values.homelab.cloudflare.externalSecret.secretKey | quote }}
        selector:
          dnsZones:
{{- range .Values.homelab.acme.dnsZones }}
            - {{ . | quote }}
{{- end }}
{{- end }}
