services:
  "{{ service_name }}":
    container_name: "{{ service_name }}"
    image: portainer/agent:latest
    restart: always
    ports:
      - 9001:9001
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
