apiVersion: v2
name: homelab-nginx
description: Wrapper around Bitnami nginx
type: application
version: 0.1.0
dependencies:
  - name: nginx
    version: 23.0.4
    repository: oci://registry-1.docker.io/bitnamicharts
